KEY_WORD("barev",       "{",      PARENTHESIS,  "{")
KEY_WORD("ST",		    "ST",     STAT,			"ST")
KEY_WORD("FUNC",        "FUNC",   FUNC,			"FUNC")
KEY_WORD("CALL",        "CALL",   CALL,		    "CALL")
KEY_WORD("PARAM",       "PARAM",  PARAM,         "PARAM")
KEY_WORD("ctesutyun",   "}",      PARENTHESIS,  "}")
KEY_WORD("ete",         "if",     IF,           "IF")
KEY_WORD("aysdepkum",   "then",   THEN,         "THEN")
KEY_WORD("hakarak",     "else",   ELSE,         "ELSE")
KEY_WORD("veradardz",   "return", RETURN,       "RET")
KEY_WORD("kani",        "while",  WHILE,        "WHILE")
KEY_WORD("verj",        ";",      STR_END,      ";"  )
KEY_WORD("gumarats",    "+",	  OP,           "ADD")
KEY_WORD("hanats",      "-",	  OP,          "SUB" )
KEY_WORD("basmapatkel", "*",	  OP,   	   "MUL" )
KEY_WORD("bajanel",     "/",      OP,          "DIV" )
KEY_WORD("sin",         "sin",    OP,          "SIN" )
KEY_WORD("cos",         "cos",    OP,          "COS" )
KEY_WORD("astijan",     "pow",	  OP,          "POW" )
KEY_WORD("ln",          "log",	  OP,          "LN"  )
KEY_WORD("axper",       "var",	  DEF,         "VAR" )
KEY_WORD("nshanakuma",   "=",     ASSIGN,      "EQ"  )
KEY_WORD("bac",         "(",	  PARENTHESIS, "("   )
KEY_WORD("pag",         ")",	  PARENTHESIS, ")"   )
KEY_WORD("tpek",		"printf", PRINTF,      "OUT" )
KEY_WORD("cardacek",    "scanf",  SCANF,       "IN"  )
KEY_WORD("storaket",    ",",      COMMA,       ","   )
KEY_WORD("datark",		"void",   RET_VAL,     "VOID")
KEY_WORD("krknaki",     "double", RET_VAL,     "TYPE")
KEY_WORD("pakas",		"<",      OP,          "IS_BT")


